DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS country;

CREATE TABLE profiles(
  id   INTEGER      NOT NULL AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  country_id int,
  PRIMARY KEY ( id )
);

CREATE TABLE country (
  id   INTEGER      NOT NULL AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  PRIMARY KEY (id)
);